# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _GymSolver
else:
    import _GymSolver

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class GymSolver(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, sat_prob, adj_mat, in_memory, with_restarts, max_decision_cap):
        _GymSolver.GymSolver_swiginit(self, _GymSolver.new_GymSolver(sat_prob, adj_mat, in_memory, with_restarts, max_decision_cap))

    def step(self, arg2):
        return _GymSolver.GymSolver_step(self, arg2)

    def set_activities(self, in_arr):
        return _GymSolver.GymSolver_set_activities(self, in_arr)

    def get_reward(self):
        return _GymSolver.GymSolver_get_reward(self)

    def get_done(self):
        return _GymSolver.GymSolver_get_done(self)

    def get_metadata(self):
        return _GymSolver.GymSolver_get_metadata(self)

    def get_assignments(self):
        return _GymSolver.GymSolver_get_assignments(self)

    def get_activities(self):
        return _GymSolver.GymSolver_get_activities(self)

    def get_clauses(self):
        return _GymSolver.GymSolver_get_clauses(self)
    __swig_destroy__ = _GymSolver.delete_GymSolver

# Register GymSolver in _GymSolver:
_GymSolver.GymSolver_swigregister(GymSolver)

